name: On Pull Request

on:
  pull_request:
  workflow_dispatch:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Rush install
        run: node common/scripts/install-run-rush.js install

      - name: Build code
        run: node common/scripts/install-run-rush.js build

      - name: Run tests
        run: node common/scripts/install-run-rush.js test --verbose
